name: Build Package RPM
on:
  repository_dispatch:
    types:
      - biglinux-RPM/*

jobs:
  build:
    runs-on: ubuntu-latest
    #container: oraclelinux:9
    steps:
      - uses: actions/checkout@v3
      - name: Build
        shell: bash
        run: |
          git clone ${{ github.event.client_payload.url }}.git
          echo ${{ github.event.client_payload.repository }} | cut -d "/" -f2
          cp -ra $(echo ${{ github.event.client_payload.repository }} | cut -d "/" -f2)/rpmbuild/ $HOME
          pushd $HOME
          rpmbuild -ba rpmbuild/SPECS/rpmbuild.spec
          
      - name: Push to Repo
        shell: bash
        run: |
          echo "## ssh setup"
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          #ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          echo "${{ secrets.PKGBUILD_KEY }}" >> /home/runner/.ssh/github_actions
          eval `ssh-agent -s`
          ssh-add /home/runner/.ssh/github_actions
          ssh-keyscan -t rsa -p ${{ secrets.PKGBUILD_PORT }} ${{ secrets.PKGBUILD_HOST }} >> /home/runner/.ssh/known_hosts
          ip=$(ssh ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }} -p ${{ secrets.PKGBUILD_PORT }} 'echo $(curl -s ident.me) | tail -n1')
          ssh-keyscan -t rsa -p ${{ secrets.PKGBUILD_PORT }} $ip >> /home/runner/.ssh/known_hosts
          
          if [ -n "$(echo ${{ github.event.client_payload.branch }} | grep stable )" ];then branch=stable; else branch=testing; fi
          # for i in *.zst *.sig *.md5; do
          pushd $HOME/rpmbuild/RPMS/x86_64/
          for i in *.rpm; do
          test -e $i && rsync -vapz -e "ssh -p ${{ secrets.PKGBUILD_PORT }}" $i ${{ secrets.PKGBUILD_USER }}@${{ secrets.PKGBUILD_HOST }}:${ip}/$branch/x86_64
          sleep 10
          done
          
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

